FROM node:20-slim AS build
WORKDIR /build
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /build/dist /srv/frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf
